### ISSUE TITLE
3 small errors in css

### ISSUE THREAD

**Issue by thomasvjohansen** [Paul-Reed/weather-icons-lite#11]
missing comma's
Proberly me who missed them in the first place.

line125:
`.wi-rotate-225,.wi-rotate-SW.wi-towards-SW,.wi-from-NE {`
should be added comma after "rotate-SW"
`.wi-rotate-225,.wi-rotate-SW,.wi-towards-SW,.wi-from-NE {`

same with line 130:
`.wi-rotate-248,.wi-rotate-WSW.wi-towards-WSW,.wi-from-ENE {`
should be added comma after "rotate-WSW"
`.wi-rotate-248,.wi-rotate-WSW,.wi-towards-WSW,.wi-from-ENE {`

and line 141
`.wi-rotate-293,.wi-rotate-WNW.wi-towards-WNW,.wi-from-ESE {`
should be added comma after "rotate-WNW"
`.wi-rotate-293,.wi-rotate-WNW,.wi-towards-WNW,.wi-from-ESE {`

**Comment by Paul-Reed** [comment]
Hi Thomas. I didn't notice them either.
I've [updated a branch with the typos](https://github.com/Paul-Reed/weather-icons-lite/tree/typos), if you find any other issues, please let me know, otherwise I'll update NPM in a few days time.

Thanks

**Comment by Paul-Reed** [comment]
https://github.com/Paul-Reed/weather-icons-lite/commit/c225546360fed377e252e47ce13c06df99315e2f now merged into master, and v1.6.1 published on NPM.
