### ISSUE TITLE
Moon Phase Icons

### ISSUE THREAD

**Issue by zimbo86** [Paul-Reed/weather-icons-lite#13]
Hi,
I can successfully add WU and Darksky Icons but when I try to add the moon phases nothing is displayed:
i class="wi wi-moon-new" style="color:white;"
What am I doing wrong here?

**Comment by zimbo86** [comment]
I´m sorry, it was related to node-red dashboard version. See here: 
https://discourse.nodered.org/t/moon-phase-icons/25802/8

**Comment by Paul-Reed** [comment]
So has updating the dashboard resolved the issue?

**Comment by Paul-Reed** [comment]
No reply from original poster
