### ISSUE TITLE
Wrong angle for rotation

### ISSUE THREAD

**Issue by Simon01011** [Paul-Reed/weather-icons-lite#14]
Hi!

In the documentation under "Styling -> Rotating icons" one of the angles is wrong. Instead of 133 it should be 113. Not a big deal, but it made me wonder that the angles worked except for this one.

Kind regards, Simon

**Comment by Paul-Reed** [comment]
Well spotted!
Now corrected via https://github.com/Paul-Reed/weather-icons-lite/commit/bc5c73d9e992acfdade49c704871f7516dfe5035

Thank you
