### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by carefulcomputer** [Paul-Reed/weather-icons-lite#4]
Can you please add some instructions on how to install this ?
Readme says that it is already included in node-red. 
However, when I imported this flow 
https://gist.github.com/djiwondee/b5b7d5da14d24e71de447e6aa290937e 
it doesn't pull in CSS and icons. I see in browser console that css is throwing 404.

**Comment by Paul-Reed** [comment]
As you are already aware, this is integrated within the node-RED dashboard.
If it's not working for you within the node-RED environment, then please post in the [node-RED forum](https://discourse.nodered.org/) when you can get support.
